### ISSUE TITLE
Image hyperlinks 

### ISSUE THREAD

**Issue by Mole1424** [UWCS/new-site#26]
Some images that are also hyperlinks have got link icons. These should be removed. ![Screenshot_20230817-215538.png](https://github.com/UWCS/new-site/assets/43819983/159422af-4de2-4478-a13c-af01076e4fab)

**Comment by ericthelemur** [comment]
Behaviour defined in `sass/custom/links.scss`, easiest way is likely to add the `int`ernal class to the link to hide it, otherwise extend the `a.int` definition to include links that have a div as a child (with `:has` most likely)
