### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Mole1424** [UWCS/new-site#27]
Intergrate the warwick compsoc google calendar with the website

**Comment by ericthelemur** [comment]
What's on the calendar other than events?

**Comment by Mole1424** [comment]
TBC (future me issue)

**Comment by Mole1424** [comment]
As Owen said this is just events. Maybe make it so that adding stuff to google calendar updates the site auto-magically or vice versa? Anyways future problem.

**Comment by ericthelemur** [comment]
The site generates an ical you can use in google calendar already, so that direction is easy. The reverse would be a real pain
