### ISSUE TITLE
Events page feedback

### ISSUE THREAD

**Issue by JoshHeng** [UWCS/new-site#40]
- [x] 1. If there are no past events, I'd add an empty state (this could probs also apply to the news/events pages too)
![image](https://github.com/UWCS/new-site/assets/34946235/15f41145-cc72-4280-97f8-845e0f30faef)

- [x] 2. Having a hover state for the schedule could be nice
![image](https://github.com/UWCS/new-site/assets/34946235/b67a0aab-de81-4d3a-8b79-8ae6bcc13800)

- [x] 3. On mobile it looks a little weird (width 320px, iPhone 5)
![image](https://github.com/UWCS/new-site/assets/34946235/822dabe4-9882-404d-8809-7542abfd11cd)

- [x] 4. Having the event date/time/location in the meta could be useful when it's being shared on social media
![image](https://github.com/UWCS/new-site/assets/34946235/7cf651eb-78db-4373-bb7a-0e0ae72d39cd)

- [x] 5. I have no idea what happened to the font here but it looks a little weird - https://new.uwcs.co.uk/events/t1/w1/fng/#
![image](https://github.com/UWCS/new-site/assets/34946235/6df7af6f-4e85-43a2-a5c3-1229ecd6dda1)

**Comment by ericthelemur** [comment]
3 is likely the same as news #1, will also fix tomorrow, 5 is because serene used unicode strikethough characters and they render strangely

**Comment by Mole1424** [comment]
all implemented
